Repository lblod/frontend-embeddable-notule-editor, pull requests merged in 2023-09, with the labels that each got.

#136 add woodpecker pipeline responsible for verifying PR
  .woodpecker/.verify-pr.yml
  config/environment.js
  tests/integration/helpers/array-includes-test.js
Labels: internal

#138 Add release-it packages
  .release-it.json
  package-lock.json
  package.json
Labels: internal

#137 Move to changesets for changelog management
  .changeset/README.md
  .changeset/config.json
  .changeset/six-chairs-flash.md
  .release-it.json
  .woodpecker/.changeset.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: internal

#142 GN-4516: solve svg cors issues
  .changeset/soft-worms-accept.md
  app/app.js
  app/components/au-icon.hbs
  app/components/au-icon.js
  config/environment.js
  ember-cli-build.js
  package-lock.json
  package.json
Labels: bug

#146 CI: ignore ember test failure for now
  .woodpecker/.verify-pr.yml
Labels: internal

#132 bump editor and update plugin configs
  .changeset/bright-suits-listen.md
  README.md
  app/components/simple-editor.hbs
  app/components/simple-editor.js
  app/models/artikel.js
  app/models/besluit.js
  app/styles/app.scss
  config/environment.js
  package-lock.json
  package.json
  public/test.html
Labels: enhancement, breaking

#152 remove citations-only sample page
  .changeset/fast-spoons-help.md
  public/citations-only.html
Labels: internal

#154 Internationalize remaining hard-coded parts of `simple-editor` component
  .changeset/long-garlics-deny.md
  .changeset/ten-zebras-deny.md
  app/components/simple-editor.hbs
  app/components/simple-editor.js
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement
